### PR TITLE
Searching a song not existing in our database automatically adds it to database

### PR DESCRIPTION
**Pull request by zenxha**
I've implemented a feature that enables users to search for songs not yet existing in our database. When a song is absent from the database, the system now automatically generates both the song document and an associated artist document. This enhancement guarantees consistency within our data model, aligning with the structured approach we've adopted. Notably, users won't need to reload the page when adding a new song; the searched song seamlessly appears, with the database update transparent to them.

### CODE REVIEW

**Comment by ajarean** [comment]
I'm having a bit of an issue with the search bar. When I search for a song, it doesn't show the dropdown menu like it should and I can't add the song. Has this been implemented yet?
image

**Comment by twu148** [comment]
I consulted with the DRI (Komay) as I was having the same issue. You need to change your local environmental variables. I will DM them to you.

**Comment by twu148** [comment]
> I'm having a bit of an issue with the search bar. When I search for a song, it doesn't show the dropdown menu like it should and I can't add the song. Has this been implemented yet? image

I consulted with the DRI (Komay) as I was having the same issue. You need to change your local environmental variables. I will DM them to you.

**Review by twu148 — COMMENTED** [review]
Good!

**Pull request merged**
